# Generated by Django 3.2.5 on 2021-08-05 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='users',
        ),
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ManyToManyField(to='Server.Server')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
