# Generated by Django 3.2.5 on 2021-08-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_auto_20210805_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverlist',
            name='server',
        ),
        migrations.AddField(
            model_name='serverlist',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Server.server'),
            preserve_default=False,
        ),
    ]
